# Uncomment the next line to define a global platform for your project
platform :osx, '10.10'

target 'Bagel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'CocoaAsyncSocket'
  pod 'macOSThemeKit', '~> 1.2.0'
  
end
